### ISSUE TITLE
Unchained Mod Links Broken

### ISSUE THREAD

**Issue by Atomikkunn** [RinLovesYou/PogManager-Unchained#1]
Clicking on any github link in the unchained mods section on startup will crash. If you go to a link in the VRCMG and then try it will just go the most recent link it sent you to.

**Comment by RinLovesYou** [comment]
Thank you for reporting this! I was sadly unable to reproduce the issue you've mentioned with the VRCMG Tab. However i've just pushed a [release](https://github.com/RinLovesYou/PogManager-Unchained/releases/latest) that adresses the Unchained link crash.

If you could elaborate a bit on the issue with the VRCMG Tab feel free to open a new issue!
